apiVersion: "kubeflow.org/v1alpha2"
kind: "MXJob"
metadata:
  name: "auto-tuning-job"
spec:
  jobMode: MXTune
  mxReplicaSpecs:
    TunerTracker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: mxnet
            image: kingonthestar/auto-tuning:1.0
            command: ["python3"]
            args: ["/home/test/startMXJob.py"]
    TunerServer:
      label: gpu1
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: mxnet
            image: kingonthestar/auto-tuning:1.0
            command: ["python3"]
            args: ["/home/test/startMXJob.py"]
            resources:
              limits:
                nvidia.com/gpu: 1
    Tuner:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: mxnet
            image: kingonthestar/auto-tuning:1.0
            command: ["python3"]
            args: ["/home/test/startMXJob.py"]